Clone branch
bren2102/newsweek-clone pull request #1
Opened 2020-02-10 17:29 UTC by bren2102

I Kindly request a code review for my [Newsweek](https://www.newsweek.com/) clone project which I developed by myself using HTML CSS and the bootstap framework.

- Added and styled Top Section
- Added and styled Main Section
- Added and styled Footer Section
- Added and styled Navbar
- Added and styled Images
- Added and styled Sticky Sections

2020-02-10 18:24 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-10 18:25 UTC, pelzolga123 commented on index.html
> +          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"  style="width: 90px; font-size: 12px;">
No inline styling. Please move all styles from `index.html` to `style.css`

2020-02-10 18:26 UTC, pelzolga123 commented on CSS/style.css
> +  margin: 0 auto; */
It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-02-10 18:27 UTC, pelzolga123 commented
## Hi Brenda! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: great!
Here is a list of things to change, before this project can be approved:
* [ ] Navigation bar needs to look more like original one:
* Laptop size:
![image](https://user-images.githubusercontent.com/20416431/74175291-30491280-4c3e-11ea-989a-cc7f732a7160.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74175370-5e2e5700-4c3e-11ea-89cf-3568b9a2c2e7.png)

* Mobile size:
![image](https://user-images.githubusercontent.com/20416431/74175693-ff1d1200-4c3e-11ea-960a-b2f0618eec31.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74175836-41465380-4c3f-11ea-97ce-37a8c564fd79.png)

* [ ] Some of your sections have very small distance between them, that needs to be corrected to look more like original. For example:
![image](https://user-images.githubusercontent.com/20416431/74176073-a8640800-4c3f-11ea-829f-0e94db999496.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74176186-e103e180-4c3f-11ea-95f9-4a11fa20a165.png)

* [ ] Next section should have same height and `newsletter` part should look more like original in large, tablet and mobile versions:
![image](https://user-images.githubusercontent.com/20416431/74176568-a0589800-4c40-11ea-8781-a164e8796d74.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74176673-d3029080-4c40-11ea-8d6c-9c60a8aae6d6.png)

* [ ] Next two sections require adjustments in mobile version:
![image](https://user-images.githubusercontent.com/20416431/74177120-c7fc3000-4c41-11ea-8597-888f5dbaee81.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74177097-b9ae1400-4c41-11ea-81f9-c2a733e21ea9.png)

* [ ] Footer in mobile version should look more like original:
![image](https://user-images.githubusercontent.com/20416431/74177432-625c7380-4c42-11ea-8b0d-151b39a0cb2f.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74177304-275a4000-4c42-11ea-87be-0d4b21ec0e2b.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-11 01:19 UTC, bren2102 commented
- No styling on HTML
- Comments deleted on CSS
- Navigation bar on mobile and web fixed 
- Distance between sections fixed
- Newsweek and Newsletter section fixed
- Latest News an Opinion section fixed
- Footer Fixed

2020-02-11 01:38 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)

2020-02-11 02:22 UTC, Oluwadamilareolusakin commented
# Fantastic work @bren2102 :clap: 
You have done a great job building this and incorporating the changes suggested by @pelzolga123 :medal_military: Please consider my comments below, make necessary changes and request a re-review :100: 

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.

Please note the following responsive issues:

#### Navbar
![screenshot](https://images2.imgbox.com/1f/92/YKnexSSy_o.png)

#### Opinion Section
![screenshot](https://images2.imgbox.com/c1/af/K8tnCvOU_o.png)

These errors were found at 1024px

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-11 04:58 UTC, bren2102 commented
- Navbar fixed
- Opinion sapce section fixed
- Categories text section

2020-02-11 08:36 UTC, rOluochKe approved these changes
Hello Team!
### Good job, I see you have made changes from previous reviews and your project looks good.
### Congratulations your project has been approved :clap: :boom:

- You can merge and submit a project completion form from your dashboard
- All the best in your next project.
- Happy coding!

2020-02-11 14:13 UTC, merged